//     const data =[
//     {
//         type:"checkbox",
//         image:[
//         {
//             image1
//         },
//         {
//             image2
//         },
//         {
//             image3
//         },
//         {
//             image4
//         }
//         ],
//         title:[
//         {
//             title1:'Shirt'
//         },
//         {
//             title1:'Pant'
//         },
//         {
//             title1:'saree'
//         },
//         {
//             title1:'others'
//         }
//         ],
//         select:[
//         {
//             label:'1',
//             value:'1'
//         },
//         {
//             label:'2',
//             value:'2'
//         },
//         {
//             label:'3',
//             value:'3'
//         },
//         {
//             label:'4',
//             value:'4'
//         }
//         ]
//     }
//     ]

// console.log(data);